cc_library(
    name = "RunfilesHelper",
    srcs = ["RunfilesHelper.cpp"],
    hdrs = ["RunfilesHelper.h"],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        "@bazel_tools//tools/cpp/runfiles",
    ],
)
