cc_test(
    name = "test",
    size = "small",
    srcs = ["test_add.cpp"],
    tags = ["unit"],
    visibility = ["//visibility:public"],
    deps = [
        "//cpp/add_module",
        "@com_google_googletest//:gtest_main",
    ],
)
