py_test(
  name = "test_pyd",
  size = "small",
  srcs = ["test_pyd.py"],
  deps = [
    "//cpp_n_python/cpp_on_python/pyd_module:MyAddModule_py"
  ],
  tags = ["unit"],
  visibility = ["//visibility:public"],
)
