# Python wrapper for foo library.
load("@rules_python//python:defs.bzl", "py_library")

py_library(
  name = "add_module",
  srcs = ["add.py"],
  deps = [],
  visibility = ["//visibility:public"],
)

py_library(
  name = "exception_module",
  srcs = ["exception_raiser.py"],
  deps = [],
  visibility = ["//visibility:public"],
)
py_library(
  name = "runfiles_module",
  srcs = ["runfiles_helper.py"],
  deps = [],
  visibility = ["//visibility:public"],
)

