cc_library(
    name = "add_module",
    srcs = ["add.cpp"],
    hdrs = ["add.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "Foo",
    srcs = ["Foo.cpp"],
    hdrs = ["Foo.h"],
    visibility = ["//visibility:public"],
)
